// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAyI0glWQppSlgSVIqcGr1wLfh5tSl04Y',
    appId: '1:605369961682:web:e9fcffa048cbaaf8bb310b',
    messagingSenderId: '605369961682',
    projectId: 'heart-desease',
    authDomain: 'heart-desease.firebaseapp.com',
    databaseURL: 'https://heart-desease-default-rtdb.firebaseio.com',
    storageBucket: 'heart-desease.appspot.com',
    measurementId: 'G-QHDM2YT432',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglJQVlYtHmnhJrfJH2VdxqT5KcAgyTNM',
    appId: '1:605369961682:android:b06df657adff3726bb310b',
    messagingSenderId: '605369961682',
    projectId: 'heart-desease',
    databaseURL: 'https://heart-desease-default-rtdb.firebaseio.com',
    storageBucket: 'heart-desease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC290l5ZAK_umk3esRozArs5G6BCZ5Abc0',
    appId: '1:605369961682:ios:25788bc94b26241cbb310b',
    messagingSenderId: '605369961682',
    projectId: 'heart-desease',
    databaseURL: 'https://heart-desease-default-rtdb.firebaseio.com',
    storageBucket: 'heart-desease.appspot.com',
    iosClientId: '605369961682-243d14qa8ccr1t8s7r8ctjn15nfdu990.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartmedic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC290l5ZAK_umk3esRozArs5G6BCZ5Abc0',
    appId: '1:605369961682:ios:25788bc94b26241cbb310b',
    messagingSenderId: '605369961682',
    projectId: 'heart-desease',
    databaseURL: 'https://heart-desease-default-rtdb.firebaseio.com',
    storageBucket: 'heart-desease.appspot.com',
    iosClientId: '605369961682-243d14qa8ccr1t8s7r8ctjn15nfdu990.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartmedic',
  );
}
